# Generated by Django 3.2.8 on 2024-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, verbose_name='X Value')),
                ('y', models.IntegerField(default=0, verbose_name='Y Value')),
            ],
        ),
    ]
